name: 17 - 1 - Custom Actions - Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "'dev' or 'prod'. Controls whether dev dependencies are installed."
        required: true
        type: choice
        options:
          - dev
          - prod
        default: dev
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env}}
env:
  working-directory: "sample-apps/react-app"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Node and NPM Dependencies
        id: setup-deps
        uses: ./.github/actions/composite-cache-deps
        with:
          working-dir: ${{ env.working-directory}}
          target-env: ${{ inputs.target-env }}
      - name: Print setup deps output
        run: |
          echo "Installed dependencies: ${{ steps.setup-deps.outputs.installed-deps }}"
          echo "Random output: ${{ steps.setup-deps.outputs.random }}"
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
