name: 17 - 2 - Custom Actions - JS
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: "The branch used as the base for the dependency update checks."
        type: string
        required: false
        default: main
      head-branch:
        description: "The branch from which the PR is created."
        type: string
        required: false
        default: update-dependencies
      working-directory:
        description: "The working directory of the project to check for dependency updates."
        required: true
        type: string
      gh-token:
        description: "Authentication token with repository access. Must have write access to contents and pull-requests."
        required: false
        type: string
      debug:
        description: "Whether the output debug messages to the console."
        type: boolean
        required: false
        default: true

run-name: "17-2 ${{ inputs.base-branch }} -> ${{ inputs.head-branch }}, pwd: ${{ inputs.working-directory }}"

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v5
      - name: Check for dependency updates
        id: js-dependency-update
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ inputs.base-branch}}
          head-branch: ${{ inputs.head-branch || 'update-dependencies'}}
          working-directory: ${{ inputs.working-directory}}
          gh-token: ${{ inputs.gh-token || secrets.GITHUB_TOKEN}}
          debug: ${{ inputs.debug || false }}
      - name: Output Results
        run: |
          echo "Updates available: ${{ steps.js-dependency-update.outputs.updates-available }}"
          echo "Pull Request URL: ${{ steps.js-dependency-update.outputs.pr-url }}"
