name: 19 - 1 - Managing Concurrency
on:
  workflow_dispatch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Ping UR
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.unreachable-site.com  # -> INPUT_URL in action's environment
          max_trials: 20  # -> INPUT_MAX_TRIALS in action's environment
          delay: 5  # -> INPUT_DELAY in action's environment