name: 20 - Workflow Security
on:
  pull_request:
jobs:
  unsafe-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check PR title
        run: |
          title=${{ github.event.pull_request.title }}
          if [[ $title =~ ^feat ]]; then
            echo "PR is a feature"
            exit 0
          else
            echo "PR is not a feature"
            exit 1
          fi